"""updated product_cart to on cascade delete the product in cart

Revision ID: 29eb072daf4b
Revises: 5530c60df38f
Create Date: 2026-06-01 11:48:06.270678

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29eb072daf4b'
down_revision: Union[str, Sequence[str], None] = '5530c60df38f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('product_cart_product_in_cart_id_fkey'), 'product_cart', type_='foreignkey')
    op.create_foreign_key(None, 'product_cart', 'product_in_cart', ['product_in_cart_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_cart', type_='foreignkey')
    op.create_foreign_key(op.f('product_cart_product_in_cart_id_fkey'), 'product_cart', 'product_in_cart', ['product_in_cart_id'], ['id'])
    # ### end Alembic commands ###
