"""update discounts

Revision ID: 432ea59dfe71
Revises: f1d897646845
Create Date: 2026-05-05 12:20:02.450256

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '432ea59dfe71'
down_revision: Union[str, Sequence[str], None] = 'f1d897646845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discounts_product_id'), table_name='discounts')
    op.drop_constraint(op.f('discounts_product_id_fkey'), 'discounts', type_='foreignkey')
    op.drop_column('discounts', 'product_id')
    op.add_column('products', sa.Column('discount_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'discounts', ['discount_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'discount_id')
    op.add_column('discounts', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('discounts_product_id_fkey'), 'discounts', 'products', ['product_id'], ['id'])
    op.create_index(op.f('ix_discounts_product_id'), 'discounts', ['product_id'], unique=False)
    # ### end Alembic commands ###
