"""updated carts to have user_id be unique

Revision ID: 5530c60df38f
Revises: 8b1696258670
Create Date: 2026-05-30 14:17:00.579970

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5530c60df38f'
down_revision: Union[str, Sequence[str], None] = '8b1696258670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carts_user_id'), table_name='carts')
    op.create_index(op.f('ix_carts_user_id'), 'carts', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carts_user_id'), table_name='carts')
    op.create_index(op.f('ix_carts_user_id'), 'carts', ['user_id'], unique=False)
    # ### end Alembic commands ###
