"""add more entities

Revision ID: f1d897646845
Revises: 780347281466
Create Date: 2026-05-04 11:53:49.179999

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1d897646845'
down_revision: Union[str, Sequence[str], None] = '780347281466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carts_user_id'), 'carts', ['user_id'], unique=False)
    op.create_table('discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discounts_end_date'), 'discounts', ['end_date'], unique=False)
    op.create_index(op.f('ix_discounts_product_id'), 'discounts', ['product_id'], unique=False)
    op.create_index(op.f('ix_discounts_start_date'), 'discounts', ['start_date'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_product_id'), 'images', ['product_id'], unique=False)
    op.create_table('product_in_cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_in_cart_product_id'), 'product_in_cart', ['product_id'], unique=False)
    op.create_table('product_cart',
    sa.Column('product_in_cart_id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['product_in_cart_id'], ['product_in_cart.id'], ),
    sa.PrimaryKeyConstraint('product_in_cart_id', 'cart_id')
    )
    op.drop_column('products', 'discount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_table('product_cart')
    op.drop_index(op.f('ix_product_in_cart_product_id'), table_name='product_in_cart')
    op.drop_table('product_in_cart')
    op.drop_index(op.f('ix_images_product_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_discounts_start_date'), table_name='discounts')
    op.drop_index(op.f('ix_discounts_product_id'), table_name='discounts')
    op.drop_index(op.f('ix_discounts_end_date'), table_name='discounts')
    op.drop_table('discounts')
    op.drop_index(op.f('ix_carts_user_id'), table_name='carts')
    op.drop_table('carts')
    # ### end Alembic commands ###
